title: ls-lrt.com
email: samirparhi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  DevOps For All
baseurl: '/' # the subpath of your site, e.g. /blog
url: https://samirparhi-dev.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: samirparhi
github_username:  samirparhi-dev
domain: samirparhi-dev.github.io
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
